config/routes.rb
NinetyNineCatsDay1::Application.routes.draw do
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    # we chose post. Patch might be semantically better
    # but now we don't need that extra hidden input to send
      # params {_method: 'patch'}

    post "approve", on: :member
    post "deny", on: :member
  end
  resources :users
  resource :session, only: [:create, :new, :destroy]

  root to: redirect("/cats")
end

app/models/cat.rb
require 'action_view'

class Cat < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  CAT_COLORS = %w(black white orange brown)

  has_many(
    :rental_requests,
    class_name: "CatRentalRequest",
    dependent: :destroy
  )

  belongs_to(
    :owner,
    class_name: "User",

    primary_key: :id,
    foreign_key: :user_id
  )

  validates(
    :birth_date,
    :color,
    :name,
    :sex,
    presence: true
  )

  validates :color, inclusion: CAT_COLORS
  validates :sex, inclusion: %w(M F)



  def age
    time_ago_in_words(birth_date)
  end


end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat)
      .permit(:age, :birth_date, :color, :description, :name, :sex)
  end

end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% action = (cat.persisted? ? cat_url(cat) : cats_url) %>
<% method = (cat.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="cat_name">Name</label>
  <input
    type="text"
    name="cat[name]"
    id="cat_name"
    value="<%= cat.name %>">

  <label for="cat_birth_date">Birth date</label>
  <input
    type="date"
    name="cat[birth_date]"
    id="cat_birth_date"
    value="<%= cat.birth_date %>">
  <br>

  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
    <option></option>
    <% Cat::CAT_COLORS.each do |color| %>
      <option
        <%= cat.color == color ? "selected" : "" %>
        value="<%= color %>">
        <%= color.upcase %>
      </option>
    <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="cat[sex]"
    value="M"
    id="cat_sex_male"
    <%= cat.sex == "M" ? "checked" : "" %>>
  <label for="cat_sex_male">Male</label>
  <input
    type="radio"
    name="cat[sex]"
    value="F"
    id="cat_sex_female"
    <%= cat.sex == "F" ? "checked" : "" %>>
  <label for="cat_sex_female">Female</label>
  <br>

  <label>
    Description
    <textarea name="cat[description]"><%= cat.description %></textarea>
  </label>

  <% submit_text = (cat.persisted? ? 'Update' : 'Create') + ' cat!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/cats/_req_tr.html.erb
<tr>
  <td><%= req.start_date %></td>
  <td><%= req.end_date %></td>
  <td>
    <% if req.pending? %>
    <!--  button_to is a rails helper method: makes-->
    <!-- <form action="<%=approve_cat_rental_request_url(req) %>" method="post">
      <input type="submit" value="Approve">
      OR
      <button>Approve</button>
    </form> -->


        <%= button_to "Approve", approve_cat_rental_request_url(req) %>
        <%= button_to "Deny", deny_cat_rental_request_url(req) %>
    <% else %>
      <%= req.status %>
    <% end %>
  </td>
</tr>

app/views/cats/edit.html.erb
<h1>Edit My Cat</h1>
<%= render "shared/errors" %>
<%= render "form", cat: @cat %>

app/views/cats/index.html.erb
<h1>Cats upon cats!</h1>

<ul>
  <% @cats.each do |cat| %>
    <li><%= link_to cat.name, cat_url(cat) %></li>
  <% end %>
</ul>

<%= link_to "Create cat", new_cat_url %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render "shared/errors" %>
<%= render "form", cat: @cat %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <th>Attribute</th>
    <th>Value</th>
  </tr>
  <% [:age, :birth_date, :color, :sex].each do |attr_name| %>
    <tr>
      <td><%= attr_name %></td>
      <td><%= @cat.send(attr_name) %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Edit #{@cat.name}", edit_cat_url(@cat) %>

<h2>Rental Requests</h2>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
  </tr>
  <% @cat.rental_requests.order("start_date").each do |req| %>
    <%= render "req_tr", req: req %>
  <% end %>
</table>